#Backpack IDs setup file
#backpackStorageBlock is a modified bedrock used as storage for backpack inventories.
#Mon Mar 31 19:53:48 BST 2025
ID_backpack=9738
ID_backpackStorageBlock=145
ID_backpack_blue=9741
ID_backpack_green=9740
ID_backpack_red=9739
ID_backpack_yellow=9742
