KeyboardToggleActive=34
KeyboardChargeItem=47
KeyboardReleaseCharge=19
BlockAggregator=128
BlockAlchemyChest=129
BlockObsAggregatorOff=130
BlockObsAggregatorOn=131
darkMatterFurnaceOffID=162
darkMatterFurnaceOnID=163
BlockDarkMatter=132
BlockInterdictionChest=133
BlockInterdictionTorch=164
BlockLocus=165
ItemPhilStoneC=27275
ItemCatalystStone=27290
ItemBaseRing=27296
ItemSoulStoneC=27273
ItemEvertide=27288
ItemVolcanite=27289
ItemAttractionRing=27292
ItemIgnitionRing=27293
ItemGrimarchRing=27294
ItemHyperkineticLens=27295
ItemSwiftWolfRing=27297
ItemHarvestRing=27298
ItemWatchOfTime=27300
ItemAlchemicalCoal=27276
ItemMobiusFuel=27277
ItemDarkMatter=27278
ItemCovalenceDust=27284
ItemDarkPickaxe=27279
ItemDarkSpade=27280
ItemDarkHoe=27281
ItemDarkSword=27282
ItemDarkAxe=27283
ItemDarkShears=27301
ItemDarkMatterArmor=27272
ItemDarkMatterHelmet=27270
ItemDarkMatterGreaves=27274
ItemDarkMatterBoots=27285
ItemEternalDensity=27302
ItemRepairCharm=27303
ItemDarkHammer=27304
ItemHyperCatalyst=27305
UseRebalancedRecipes=false
UsePhilStoneRecipes=false
UseCasualRebalancedRecipes=true
