#Portal Gun 1.7.3v5 - Global Settings
#Tue Jul 12 13:32:32 BST 2022
serenadeWhenSeen=0
AFPredstone=0
spawnerPower=0
unportalbleID=0
unportalbleMode=1
turretDrops=0
portalrecord2ID=2012
customPortalColour=0
gridMode=1
portalgunrebootKey=19
lockKeyAFP=0
portalblockID=104
gridBox=1
portalrecordID=2013
portalsignID=109
portalafpID=112
turretExplosionMag=15
turretShootsGlass=1
gunRespawn=0
checkpointErasesPortals=0
portalgunswapKey=34
portal2recordID=2011
turretRange=50
autoKillAPG=0
turretMode=1
portalsOverlay=2
serenadeRange=75
gunMode=1
turretHurts=1
checkpointMessage=0
portalspawnerID=110
portalbaseitemsID=13200
portalgridID=106
differentChance=10
checkpointMode=1
customColour2=\#ffffff
customColour1=\#ffffff
autoMergeGuns=1
swingArm=0
portalhepcID=108
hepMode=1
portalcheckpointID=111
portalheptID=107
portalcubeID=105
enableCheckpoints=1
haveAchievements=0
throughGlass=0
isRadioInvincible=0
isResetKeyEnabled=1
dualPortals=1
