#WirelessRedstone Properties
#Wed Jul 02 20:35:35 BST 2025
WirelessRedstone.ReceiverID=31958
WirelessRemote.RemoteID=6245
WirelessSniffer.SnifferID=6244
WirelessTriangulator.TriangulatorID=6246
PowerConfigurator.PowerConfID=6243
WirelessClocker.ClockID=31956
WirelessRedstone.TransmitterID=31957
